import { DesignProject, AboutContent } from './types';

export const DEFAULT_ABOUT_CONTENT: AboutContent = {
  profileImageUrl: '/anantica.jpg',
  name: 'Anantica Singh',
  tagline: 'Former Senior Product Manager at Google · Now making ceramics in Oakland, CA.',
  location: 'Oakland, CA',
  bioHeadline: 'After 18 years building products used by billions at Google, I stepped away from tech to work with my hands. These days I spend my time at the wheel, exploring clay as a medium for creativity and calm.',
  bioParagraphs: [
    'At Google, I co-founded the food ordering marketplace across Search, Maps, and Assistant, led AI product strategy, and shipped experiences that touched billions of users. I started my career as a photojournalist at The Times of India — visual storytelling has always been part of who I am.',
    'Now I\'m channeling that creative energy into ceramics — hand-thrown and hand-built pieces that bring warmth and intention to everyday life. It turns out the discipline of shipping products and the patience of working with clay have more in common than you\'d think.',
    'In 2026, I joined the Board of Directors of the Scratch Foundation, supporting the next generation of creative thinkers through technology and education.',
  ],
  workHistory: [
    { company: 'Scratch Foundation', role: 'Board of Directors', years: '2026 – Present' },
    { company: 'Studio Practice', role: 'Ceramicist', years: '2025 – Present' },
    { company: 'Google', role: 'GPM, AI Product Velocity, Search', years: '2024 – 2025' },
    { company: 'Google', role: 'Product Lead, Integrity Identity & Applied AI', years: '2023 – 2024' },
    { company: 'Google', role: 'Co-Founder & GPM, Food Ordering', years: '2016 – 2023' },
    { company: 'Google', role: 'PM/Lead: Growth, Core UX & Strategic Features', years: '2011 – 2016' },
    { company: 'Google', role: 'Growth Marketing Lead', years: '2007 – 2011' },
    { company: 'The Times of India', role: 'Photojournalist', years: '2002 – 2005' },
  ],
  education: [
    { school: 'Stanford University Graduate School of Business', degree: 'LEAD — Class of 2025, Strategy & Business Education' },
    { school: 'The Wharton School', degree: 'Strategy & Marketing Exec Program' },
    { school: 'The London School of Economics and Political Science (LSE)', degree: 'MSc. International Political Economy' },
    { school: "St. Xavier's College", degree: 'BA, Triple Honors in Economics, Political Science and Sociology' },
  ],
  skills: ['Ceramics', 'Hand Throwing', 'Glaze Development', 'Product Strategy', 'Visual Storytelling'],
  philosophy: 'Finding beauty in the handmade. After years of building at scale, I\'m learning to slow down and let the material lead.',
  linkedinUrl: 'https://www.linkedin.com/in/anantica',
  linkedinHandle: '/anantica',
  websiteUrl: '',
  websiteDisplay: '',
  behanceUrl: '',
  contactEmail: 'hello@anantica.com',
  contactHeadline: "Let's connect.",
  contactDescription: "Interested in ceramics, collaborations, or just want to say hello? I'd love to hear from you.",
};

export const INITIAL_PROJECTS: DesignProject[] = [
  {
    id: '1',
    title: 'Wheel-Thrown Vessels',
    category: 'Ceramics',
    imageUrl: 'https://picsum.photos/seed/wheel-thrown/800/1000',
    description: 'Exploring form and balance on the potter\'s wheel — vases, bowls, and cups shaped by hand with an emphasis on organic simplicity.',
    sortOrder: 0,
  },
  {
    id: '2',
    title: 'Glaze Experiments',
    category: 'Ceramics',
    imageUrl: 'https://picsum.photos/seed/glaze-work/800/600',
    description: 'Developing original glazes through experimentation with oxides, ash, and layering techniques. Each firing is a small discovery.',
    sortOrder: 1,
  },
  {
    id: '3',
    title: 'Hand-Built Sculpture',
    category: 'Ceramics',
    imageUrl: 'https://picsum.photos/seed/hand-built/800/1200',
    description: 'Sculptural pieces built by hand using coil and slab techniques — exploring texture, negative space, and the beauty of imperfection.',
    sortOrder: 2,
  },
  {
    id: '4',
    title: 'Functional Tableware',
    category: 'Ceramics',
    imageUrl: 'https://picsum.photos/seed/tableware/800/1000',
    description: 'Plates, mugs, and serving pieces designed to be used and loved daily. Made with care, meant to be part of everyday rituals.',
    sortOrder: 3,
  },
  {
    id: '5',
    title: 'Food Ordering on Google',
    category: 'Google · Product',
    imageUrl: 'https://picsum.photos/seed/food-ordering/800/800',
    description: 'Co-founded Google\'s food ordering marketplace across Search, Maps & Assistant. One of the proudest chapters of my tech career.',
    sortOrder: 4,
  },
  {
    id: '6',
    title: 'Google Search Redesign',
    category: 'Google · Product',
    imageUrl: 'https://picsum.photos/seed/search-redesign/800/1200',
    description: 'Led major evolutions of Google Search globally — launching the new logo, modernizing results from links to cards, and introducing Material Design.',
    sortOrder: 5,
  },
  {
    id: '7',
    title: 'Times of India',
    category: 'Photojournalism',
    imageUrl: 'https://picsum.photos/seed/times-india/800/1300',
    description: 'Visual storytelling as a photojournalist at Mumbai Times. Where the creative journey began.',
    sortOrder: 6,
  },
];
